# Generated by Django 3.2 on 2021-04-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('username', models.SlugField(blank=True, null=True)),
                ('cod_student', models.IntegerField(unique=True, verbose_name='')),
                ('aprooved', models.BooleanField(default=False, verbose_name='')),
                ('average_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=150, verbose_name='Lab name')),
                ('lab_seats', models.IntegerField(verbose_name='')),
                ('students', models.ManyToManyField(to='lab.Student', verbose_name='students_lab')),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
            },
        ),
    ]
